---
apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  namespace: "wikijs"
  name: "wikijs-ingress"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size:  "50m"
spec:
  rules:
  - host: "wiki.fortytwobinary.com"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: "wikijs"
              port:
                number: 3000
  tls:
  - hosts:
    - "wiki.fortytwobinary.com"
    secretName: "wikijs-prod-tls"
---
