---
apiVersion: v1
kind: Pod
metadata:
  name: apache 
  labels:
    run: apache
spec:
  containers:
  - image: httpd 
    name: apache 
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: "/usr/local/apache2/htdocs"
      name: www-data
  initContainers:
  - name: git-cloner
    image: alpine/git
    args:
        - clone
        - --single-branch
        - --
        - https://github.com/dlwhitehurst/hello.git
        - /data
    volumeMounts:
    - mountPath: /data
      name: www-data
  volumes:
  - name: www-data
    emptyDir: {}
